// [
//     { field: 'type' },
//     { field: 'ref' },
//     { field: 'submissionDateTime' },
//     { field: 'name' },
//     { field: 'familyName' },
//     { field: 'gender' },    
//     { field: 'age' },
//     { field: 'nationality' },
//      {field:'countryOrigin'},
//      {field:'residenceCountry'},
//     { field: 'flightNum' }, 
//     { field: 'arrivalDate' },
//     { field: 'image' }, 
// ];


export const rowData = [
    { type: 'Standard' , 
    ref: '33FG44CX', 
    submissionDateTime: new Date("October 13, 2014 11:13:00") ,
    name: 'Willeke' , 
    familyName: 'DE BRUIN', 
    gender: 'Female' , 
    age: 37, 
    nationality: 'NLD' ,
    countryOrigin: 'Lebanon',
    residenceCountry: 'Algeria', 
    flightNum: 'AF 456', 
    arrivalDate: new Date("October 20, 2020") , 
    image: 'https://cdn.pixabay.com/photo/2018/09/11/18/20/men-3670197_960_720.jpg', 
    },

    { type: 'Standard' , 
    ref: 'FH76NM99', 
    submissionDateTime: new Date("October 13, 2014 11:13:00") ,
    name: 'Sami' , 
    familyName: 'MARTIN', 
    gender: 'Female' , 
    age: 26, 
    nationality: 'NLD' ,
    countryOrigin: 'Syria',
    residenceCountry: 'Algeria', 
    flightNum: 'AF 456', 
    arrivalDate: new Date("October 20, 2020") , 
    image: 'https://cdn.pixabay.com/photo/2017/08/12/18/31/male-2634974_960_720.jpg', 
    },

    { type: 'Standard' , 
    ref: 'II23WW40', 
    submissionDateTime: new Date("October 13, 2014 11:13:00") ,
    name: 'ISMAIL' , 
    familyName: 'BINALI', 
    gender: 'Female' , 
    age: 45, 
    nationality: 'NLD' ,
    countryOrigin: 'Lebanon',
    residenceCountry: 'Palestine',  
    flightNum: 'AF 456', 
    arrivalDate: new Date("October 20, 2020") , 
    image: 'https://cdn.pixabay.com/photo/2016/03/26/20/35/young-man-1281282_960_720.jpg', 
    },

    { type: 'Standard' , 
    ref: 'II78BB43', 
    submissionDateTime: new Date("October 13, 2014 11:13:00") ,
    name: 'CHRISTIAN' , 
    familyName: 'ZERBIAN', 
    gender: 'Female' , 
    age: 60, 
    nationality: 'NLD' ,
    countryOrigin: 'Lebanon',
    residenceCountry: 'Kuwait',  
    flightNum: 'AF 456', 
    arrivalDate: new Date("October 20, 2020") , 
    image: 'https://cdn.pixabay.com/photo/2016/11/20/09/15/people-1842334_960_720.jpg', 
    },

    { type: 'Standard' , 
    ref: '99NN67VV', 
    submissionDateTime: new Date("October 13, 2014 11:13:00") ,
    name: 'KAMILA' , 
    familyName: 'RIHOVA', 
    gender: 'Female' , 
    age: 55, 
    nationality: 'NLD' ,
    countryOrigin: 'Lebanon',
    residenceCountry: 'Korea', 
    flightNum: 'AF 456', 
    arrivalDate: new Date("October 20, 2020") , 
    image: 'https://cdn.pixabay.com/photo/2016/01/18/13/07/man-1146530_960_720.jpg', 
    },

    { type: 'Standard' , 
    ref: '33FG44CX', 
    submissionDateTime: new Date("October 13, 2014 11:13:00") ,
    name: 'ZIAD' , 
    familyName: 'MOGHRABI', 
    gender: 'Female' , 
    age: 55, 
    nationality: 'NLD' , 
    countryOrigin: 'Austria',
    residenceCountry: 'Algeria', 
    flightNum: 'AF 456', 
    arrivalDate: new Date("November 10, 2009") , 
    image: 'https://cdn.pixabay.com/photo/2019/08/06/00/46/black-and-white-4387130_960_720.jpg', 
    },

    { type: 'Standard' , 
    ref: '33FG44CX', 
    submissionDateTime: new Date("October 13, 2014 11:13:00") ,
    name: 'LISANDRO' , 
    familyName: 'BARROS', 
    gender: 'Female' , 
    age: 55, 
    nationality: 'NLD' , 
    countryOrigin: 'Lebanon',
    residenceCountry: 'USA', 
    flightNum: 'AF 456', 
    arrivalDate: new Date("November 14, 2020") , 
    image: 'https://cdn.pixabay.com/photo/2016/11/11/04/19/sport-1815798_960_720.jpg', 
    },

    { type: 'Standard' , 
    ref: '66HH99XX', 
    submissionDateTime: new Date("October 11, 2015 12:13:00") ,
    name: 'MARCO' , 
    familyName: 'BIELSA', 
    gender: 'Man' , 
    age: 55, 
    nationality: 'BEL' , 
    countryOrigin: 'China',
    residenceCountry: 'Algeria', 
    flightNum: 'AF 233', 
    arrivalDate: new Date("October 21, 2019") , 
    image: 'https://cdn.pixabay.com/photo/2018/07/21/11/45/man-3552371_960_720.jpg', 
    },
];